// Generated by dev/scripts/vendor-notebook-assets.sh.
// Maki 2.1.0 icons whose names end in `-15` (the size Plotly requests).
// Do not edit by hand.

/// SVG bytes for a Maki icon file name (`marker-15.svg`), or `None`.
#[allow(clippy::too_many_lines)] // generated match, one arm per icon
pub fn maki_icon(name: &str) -> Option<&'static [u8]> {
    match name {
        "aerialway-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/aerialway-15.svg"
        )),
        "airfield-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/airfield-15.svg"
        )),
        "airport-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/airport-15.svg"
        )),
        "alcohol-shop-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/alcohol-shop-15.svg"
        )),
        "america-football-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/america-football-15.svg"
        )),
        "amusement-park-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/amusement-park-15.svg"
        )),
        "aquarium-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/aquarium-15.svg"
        )),
        "art-gallery-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/art-gallery-15.svg"
        )),
        "attraction-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/attraction-15.svg"
        )),
        "bakery-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/bakery-15.svg"
        )),
        "bank-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/bank-15.svg")),
        "bar-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/bar-15.svg")),
        "baseball-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/baseball-15.svg"
        )),
        "basketball-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/basketball-15.svg"
        )),
        "beer-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/beer-15.svg")),
        "bicycle-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/bicycle-15.svg"
        )),
        "bicycle-share-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/bicycle-share-15.svg"
        )),
        "blood-bank-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/blood-bank-15.svg"
        )),
        "buddhism-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/buddhism-15.svg"
        )),
        "building-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/building-15.svg"
        )),
        "bus-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/bus-15.svg")),
        "cafe-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/cafe-15.svg")),
        "campsite-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/campsite-15.svg"
        )),
        "car-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/car-15.svg")),
        "castle-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/castle-15.svg"
        )),
        "cemetery-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/cemetery-15.svg"
        )),
        "central-building-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/central-building-15.svg"
        )),
        "cinema-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/cinema-15.svg"
        )),
        "circle-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/circle-15.svg"
        )),
        "circle-stroked-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/circle-stroked-15.svg"
        )),
        "clothing-store-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/clothing-store-15.svg"
        )),
        "college-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/college-15.svg"
        )),
        "commercial-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/commercial-15.svg"
        )),
        "cricket-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/cricket-15.svg"
        )),
        "cross-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/cross-15.svg"
        )),
        "dam-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/dam-15.svg")),
        "danger-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/danger-15.svg"
        )),
        "dentist-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/dentist-15.svg"
        )),
        "doctor-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/doctor-15.svg"
        )),
        "dog-park-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/dog-park-15.svg"
        )),
        "drinking-water-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/drinking-water-15.svg"
        )),
        "embassy-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/embassy-15.svg"
        )),
        "entrance-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/entrance-15.svg"
        )),
        "farm-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/farm-15.svg")),
        "fast-food-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/fast-food-15.svg"
        )),
        "ferry-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/ferry-15.svg"
        )),
        "fire-station-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/fire-station-15.svg"
        )),
        "fuel-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/fuel-15.svg")),
        "gaming-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/gaming-15.svg"
        )),
        "garden-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/garden-15.svg"
        )),
        "garden-center-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/garden-center-15.svg"
        )),
        "gift-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/gift-15.svg")),
        "golf-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/golf-15.svg")),
        "grocery-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/grocery-15.svg"
        )),
        "hairdresser-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/hairdresser-15.svg"
        )),
        "harbor-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/harbor-15.svg"
        )),
        "heart-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/heart-15.svg"
        )),
        "heliport-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/heliport-15.svg"
        )),
        "hospital-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/hospital-15.svg"
        )),
        "ice-cream-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/ice-cream-15.svg"
        )),
        "industry-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/industry-15.svg"
        )),
        "information-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/information-15.svg"
        )),
        "karaoke-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/karaoke-15.svg"
        )),
        "landmark-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/landmark-15.svg"
        )),
        "laundry-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/laundry-15.svg"
        )),
        "library-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/library-15.svg"
        )),
        "lighthouse-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/lighthouse-15.svg"
        )),
        "lodging-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/lodging-15.svg"
        )),
        "marker-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/marker-15.svg"
        )),
        "monument-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/monument-15.svg"
        )),
        "mountain-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/mountain-15.svg"
        )),
        "museum-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/museum-15.svg"
        )),
        "music-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/music-15.svg"
        )),
        "park-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/park-15.svg")),
        "parking-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/parking-15.svg"
        )),
        "parking-garage-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/parking-garage-15.svg"
        )),
        "pharmacy-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/pharmacy-15.svg"
        )),
        "picnic-site-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/picnic-site-15.svg"
        )),
        "pitch-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/pitch-15.svg"
        )),
        "place-of-worship-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/place-of-worship-15.svg"
        )),
        "playground-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/playground-15.svg"
        )),
        "police-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/police-15.svg"
        )),
        "post-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/post-15.svg")),
        "prison-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/prison-15.svg"
        )),
        "rail-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/rail-15.svg")),
        "rail-light-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/rail-light-15.svg"
        )),
        "rail-metro-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/rail-metro-15.svg"
        )),
        "ranger-station-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/ranger-station-15.svg"
        )),
        "religious-christian-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/religious-christian-15.svg"
        )),
        "religious-jewish-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/religious-jewish-15.svg"
        )),
        "religious-muslim-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/religious-muslim-15.svg"
        )),
        "residential-community-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/residential-community-15.svg"
        )),
        "restaurant-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/restaurant-15.svg"
        )),
        "roadblock-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/roadblock-15.svg"
        )),
        "rocket-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/rocket-15.svg"
        )),
        "school-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/school-15.svg"
        )),
        "shelter-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/shelter-15.svg"
        )),
        "shop-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/shop-15.svg")),
        "skiing-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/skiing-15.svg"
        )),
        "soccer-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/soccer-15.svg"
        )),
        "square-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/square-15.svg"
        )),
        "square-stroked-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/square-stroked-15.svg"
        )),
        "stadium-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/stadium-15.svg"
        )),
        "star-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/star-15.svg")),
        "star-stroked-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/star-stroked-15.svg"
        )),
        "suitcase-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/suitcase-15.svg"
        )),
        "sushi-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/sushi-15.svg"
        )),
        "swimming-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/swimming-15.svg"
        )),
        "teahouse-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/teahouse-15.svg"
        )),
        "telephone-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/telephone-15.svg"
        )),
        "tennis-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/tennis-15.svg"
        )),
        "theatre-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/theatre-15.svg"
        )),
        "toilet-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/toilet-15.svg"
        )),
        "town-hall-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/town-hall-15.svg"
        )),
        "triangle-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/triangle-15.svg"
        )),
        "triangle-stroked-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/triangle-stroked-15.svg"
        )),
        "veterinary-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/veterinary-15.svg"
        )),
        "volcano-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/volcano-15.svg"
        )),
        "warehouse-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/warehouse-15.svg"
        )),
        "waste-basket-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/waste-basket-15.svg"
        )),
        "water-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/water-15.svg"
        )),
        "wetland-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/wetland-15.svg"
        )),
        "wheelchair-15.svg" => Some(include_bytes!(
            "../../assets/vendor/maki/icons/wheelchair-15.svg"
        )),
        "zoo-15.svg" => Some(include_bytes!("../../assets/vendor/maki/icons/zoo-15.svg")),
        _ => None,
    }
}
