//! GitHub-friendly Markdown emitter.
//!
//! Walks executed notebook blocks and produces a single `.md` document with
//! each captured plot written as an SVG file on disk and referenced inline
//! with `![plot N](relative/path.svg)`. GitHub's web UI renders the result
//! directly: prose as markdown, code as fenced blocks, plots as inline SVG.
//!
//! The emitter never touches Plotly or HTML — for the interactive form, use
//! the HTML output format instead.

use crate::execute::Rendered;
use crate::parse::CalloutKind;
use rustlab_plot::theme::ThemeColors;
use std::path::Path;

/// Render executed notebook blocks into a Markdown document string.
///
/// Plot images are written to `plot_dir` as SVG files and referenced from
/// the rendered `.md` using `plot_href_prefix`, which is the relative path
/// from the markdown file's directory to the plot directory. Splitting the
/// two lets callers nest plots under a single `plots/<stem>/` umbrella
/// (or any other layout) without coupling the on-disk path to the
/// markdown reference.
///
/// The `title` argument is not emitted as a heading: Markdown documents
/// conventionally express their title as the first `#` line, which the
/// source notebook already provides. The `title` is kept in the signature
/// for API parity with the other emitters and is available for future
/// needs (e.g. writing into a frontmatter block).
pub fn render_markdown(
    _title: &str,
    blocks: &[Rendered],
    plot_dir: &Path,
    plot_href_prefix: &str,
    theme: &ThemeColors,
) -> String {
    let mut body = String::new();
    let mut plot_idx = 0usize;

    // Ensure plot directory exists.
    let _ = std::fs::create_dir_all(plot_dir);
    let href_prefix = plot_href_prefix.trim_end_matches('/').to_string();

    body.push_str("<!-- Generated by rustlab-notebook — do not edit directly. -->\n\n");

    for block in blocks {
        match block {
            Rendered::Markdown(md) => {
                body.push_str(md.trim_end());
                if !body.ends_with("\n\n") {
                    body.push_str("\n\n");
                }
            }
            Rendered::Code {
                source,
                text_output,
                error,
                figures,
                hidden,
                details,
                grid_cols: _,
            } => {
                if !hidden {
                    body.push_str("```rustlab\n");
                    body.push_str(source.trim_end());
                    body.push_str("\n```\n\n");
                }

                if let Some(heading) = details {
                    body.push_str(&format!("<details>\n<summary>{}</summary>\n\n", heading));
                }

                let trimmed_out = text_output.trim();
                if !trimmed_out.is_empty() {
                    body.push_str("```text\n");
                    body.push_str(trimmed_out);
                    body.push_str("\n```\n\n");
                }

                if let Some(err) = error {
                    body.push_str("```text\n");
                    body.push_str("error: ");
                    body.push_str(err.trim_end());
                    body.push_str("\n```\n\n");
                }

                for fig in figures {
                    plot_idx += 1;
                    let plot_file = plot_dir.join(format!("plot-{plot_idx}.svg"));
                    if let Err(e) = rustlab_plot::render_figure_state_to_file_themed(
                        fig,
                        &plot_file.to_string_lossy(),
                        theme,
                    ) {
                        eprintln!("warning: could not render plot-{plot_idx}: {e}");
                        continue;
                    }
                    body.push_str(&format!(
                        "![plot {plot_idx}]({}/plot-{plot_idx}.svg)\n\n",
                        href_prefix
                    ));
                }

                if details.is_some() {
                    body.push_str("</details>\n\n");
                }
            }
            Rendered::Callout { kind, content } => {
                let label = match kind {
                    CalloutKind::Note => "Note",
                    CalloutKind::Tip => "Tip",
                    CalloutKind::Warning => "Warning",
                };
                body.push_str(&format!("> **{label}:** "));
                // Blockquote the content; preserve internal newlines with "> ".
                let indented = content.trim().replace('\n', "\n> ");
                body.push_str(&indented);
                body.push_str("\n\n");
            }
            Rendered::ExerciseStart { number } => {
                body.push_str(&format!("**Exercise {number}.** "));
            }
            Rendered::SolutionStart => {
                body.push_str("<details>\n<summary>Solution</summary>\n\n");
            }
        }
    }

    body
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::execute::Rendered;
    use rustlab_plot::Theme;

    fn tmp_plot_dir() -> std::path::PathBuf {
        let p = std::env::temp_dir().join(format!(
            "rustlab_md_plots_{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&p);
        p
    }

    fn theme() -> &'static ThemeColors {
        Theme::Dark.colors()
    }

    #[test]
    fn generated_banner_is_emitted() {
        let md = render_markdown("Hello", &[], &tmp_plot_dir(), "img", theme());
        assert!(md.contains("Generated by rustlab-notebook"));
        // No synthetic H1 — that comes from the source notebook.
        assert!(!md.contains("# Hello\n"));
    }

    #[test]
    fn markdown_passthrough() {
        let blocks = vec![Rendered::Markdown(
            "## Section\n\nSome *prose* with `code`.".to_string(),
        )];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(md.contains("## Section"));
        assert!(md.contains("*prose*"));
        assert!(md.contains("`code`"));
    }

    #[test]
    fn code_block_emits_rustlab_fence() {
        let blocks = vec![Rendered::Code {
            source: "x = 42".to_string(),
            text_output: String::new(),
            error: None,
            figures: Vec::new(),
            hidden: false,
            details: None,
            grid_cols: None,
        }];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(md.contains("```rustlab\nx = 42\n```"));
    }

    #[test]
    fn hidden_source_is_suppressed_but_output_shown() {
        let blocks = vec![Rendered::Code {
            source: "secret = 42".to_string(),
            text_output: "answer: 42".to_string(),
            error: None,
            figures: Vec::new(),
            hidden: true,
            details: None,
            grid_cols: None,
        }];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(!md.contains("secret = 42"));
        assert!(md.contains("```text\nanswer: 42\n```"));
    }

    #[test]
    fn error_is_rendered_as_code_block() {
        let blocks = vec![Rendered::Code {
            source: "oops".to_string(),
            text_output: String::new(),
            error: Some("undefined variable 'x'".to_string()),
            figures: Vec::new(),
            hidden: false,
            details: None,
            grid_cols: None,
        }];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(md.contains("error: undefined variable 'x'"));
    }

    #[test]
    fn callout_becomes_blockquote() {
        let blocks = vec![Rendered::Callout {
            kind: CalloutKind::Note,
            content: "Pay attention here.".to_string(),
        }];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(md.contains("> **Note:** Pay attention here."));
    }

    #[test]
    fn solution_wraps_in_details() {
        let blocks = vec![Rendered::SolutionStart];
        let md = render_markdown("T", &blocks, &tmp_plot_dir(), "img", theme());
        assert!(md.contains("<details>"));
        assert!(md.contains("<summary>Solution</summary>"));
    }

    #[test]
    fn plot_reference_uses_relative_path() {
        // Build a minimal FigureState with a single line series so the SVG
        // writer actually produces output.
        use rustlab_plot::{FigureState, SeriesColor};
        let mut fig = FigureState::new();
        fig.current_mut().series.push(rustlab_plot::Series {
            label: "s".to_string(),
            x_data: vec![0.0, 1.0],
            y_data: vec![0.0, 1.0],
            color: SeriesColor::Blue,
            style: rustlab_plot::LineStyle::Solid,
            kind: rustlab_plot::PlotKind::Line,
        });
        let blocks = vec![Rendered::Code {
            source: "plot([0, 1])".to_string(),
            text_output: String::new(),
            error: None,
            figures: vec![fig],
            hidden: false,
            details: None,
            grid_cols: None,
        }];
        let plot_dir = tmp_plot_dir();
        // Use a multi-segment relative href to verify the prefix is taken
        // verbatim and not derived from the plot directory's basename.
        let md = render_markdown("T", &blocks, &plot_dir, "plots/quick_look", theme());
        assert!(md.contains("![plot 1](plots/quick_look/plot-1.svg)"));
        assert!(plot_dir.join("plot-1.svg").exists());
        let _ = std::fs::remove_dir_all(&plot_dir);
    }
}
