#!/usr/bin/env bash
# Fetch and vendor the third-party JS/CSS/font assets that the interactive
# `rustlab-notebook watch` server embeds via `include_bytes!`.
#
# Re-run this script when bumping pinned versions. Outputs land in
#   crates/rustlab-notebook/assets/vendor/{katex,plotly,codemirror}/
#
# See dev/plans/notebook_interactive_server.md (locked-in #15, #16) for the
# self-contained-binary + licensing rationale. CodeMirror is the editor
# served only under `rustlab-notebook watch --editable` (Phase 5c).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VENDOR_DIR="${REPO_ROOT}/crates/rustlab-notebook/assets/vendor"

# Pinned versions — keep in sync with the URLs hard-coded in
# crates/rustlab-notebook/src/render.rs (currently lines 308-311).
KATEX_VERSION="0.16.21"
PLOTLY_VERSION="2.35.0"
CODEMIRROR_VERSION="5.65.19"

KATEX_URL="https://github.com/KaTeX/KaTeX/releases/download/v${KATEX_VERSION}/katex.tar.gz"
PLOTLY_URL="https://cdn.plot.ly/plotly-${PLOTLY_VERSION}.min.js"
CODEMIRROR_CDN="https://cdnjs.cloudflare.com/ajax/libs/codemirror/${CODEMIRROR_VERSION}"
CODEMIRROR_LICENSE_URL="https://raw.githubusercontent.com/codemirror/codemirror5/${CODEMIRROR_VERSION}/LICENSE"

KATEX_DIR="${VENDOR_DIR}/katex"
PLOTLY_DIR="${VENDOR_DIR}/plotly"
CODEMIRROR_DIR="${VENDOR_DIR}/codemirror"

# ── KaTeX ──────────────────────────────────────────────────────────────────────
echo "→ fetching KaTeX ${KATEX_VERSION}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
curl -fsSL "${KATEX_URL}" -o "${TMP}/katex.tar.gz"
tar -xzf "${TMP}/katex.tar.gz" -C "${TMP}"
# Wipe and refill so removed upstream files don't linger.
rm -rf "${KATEX_DIR}"
mkdir -p "${KATEX_DIR}"
# Copy the subset we actually serve: CSS + JS + auto-render + fonts dir.
# (KaTeX tarball also ships .map files, .mjs alternates, and contrib extras
# we don't need; keeping the vendored set minimal.)
cp "${TMP}/katex/katex.min.css"                  "${KATEX_DIR}/"
cp "${TMP}/katex/katex.min.js"                   "${KATEX_DIR}/"
mkdir -p "${KATEX_DIR}/contrib"
cp "${TMP}/katex/contrib/auto-render.min.js"     "${KATEX_DIR}/contrib/"
cp -R "${TMP}/katex/fonts"                       "${KATEX_DIR}/"
# License files from the upstream tarball.
cp "${TMP}/katex/README.md"                      "${KATEX_DIR}/README.upstream.md" 2>/dev/null || true
# KaTeX ships a single LICENSE for the JS/CSS (MIT). Fonts are OFL — we add
# a separate LICENSE.OFL.txt below.

# ── Plotly ─────────────────────────────────────────────────────────────────────
echo "→ fetching Plotly ${PLOTLY_VERSION}"
rm -rf "${PLOTLY_DIR}"
mkdir -p "${PLOTLY_DIR}"
curl -fsSL "${PLOTLY_URL}" -o "${PLOTLY_DIR}/plotly.min.js"

# ── CodeMirror 5 (editor; served only under --editable) ─────────────────────────
echo "→ fetching CodeMirror ${CODEMIRROR_VERSION}"
rm -rf "${CODEMIRROR_DIR}"
mkdir -p "${CODEMIRROR_DIR}/mode/markdown"
# Minified single-file build from cdnjs + the markdown mode. cdnjs is not on
# every sandbox network allowlist, so this fetch may need a sandbox bypass
# (same situation as the Plotly CDN fetch above).
curl -fsSL "${CODEMIRROR_CDN}/codemirror.min.js"               -o "${CODEMIRROR_DIR}/codemirror.min.js"
curl -fsSL "${CODEMIRROR_CDN}/codemirror.min.css"              -o "${CODEMIRROR_DIR}/codemirror.min.css"
curl -fsSL "${CODEMIRROR_CDN}/mode/markdown/markdown.min.js"   -o "${CODEMIRROR_DIR}/mode/markdown/markdown.min.js"
curl -fsSL "${CODEMIRROR_LICENSE_URL}"                         -o "${CODEMIRROR_DIR}/LICENSE"

# ── SHA256 + size manifest ─────────────────────────────────────────────────────
echo "→ writing SHA256 manifest"
(
    cd "${VENDOR_DIR}"
    {
        echo "# Vendored asset checksums"
        echo "# Generated by dev/scripts/vendor-notebook-assets.sh"
        echo "# KaTeX ${KATEX_VERSION}  (${KATEX_URL})"
        echo "# Plotly ${PLOTLY_VERSION} (${PLOTLY_URL})"
        echo "# CodeMirror ${CODEMIRROR_VERSION} (${CODEMIRROR_CDN})"
        echo
        find katex plotly codemirror -type f \! -name SHA256SUMS -print0 \
            | xargs -0 shasum -a 256
    } > SHA256SUMS
)

echo "✓ vendored under ${VENDOR_DIR}"
du -sh "${VENDOR_DIR}/katex" "${VENDOR_DIR}/plotly" "${VENDOR_DIR}/codemirror"
